### ISSUE TITLE
Docker file missing: gscgroup_omm.cfg

### ISSUE THREAD

**Issue by IgorSiilva** [enmotech/enmotech-docker-opengauss#59]
Anyone have a suggestion to solve this? i already tried to create the file using copy

```
version: "3"
services:
  sales-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: sales_api_local
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/home/node/app
      - ./dist:/home/node/app/dist
    networks:
      - sales-api-network
    depends_on:
      - gaussdb
        
  gaussdb:
    image: enmotech/opengauss:3.0.0
    container_name: gaussdb
    privileged: true
    environment:
      - GS_PASSWORD=Secretpassword@123
      - GS_USER=gaussdb
      - GS_DB=postgres
      - GS_PORT=5432
      - GAUSSLOG=/var/log/opengauss
      - GAUSSHOME=/usr/local/opengauss
    volumes:
      - gaussdb_data:/var/lib/opengauss
      - gaussdb_logs:/var/log/opengauss
      - ./config/gscgroup_omm.cfg:/usr/local/opengauss/etc/gscgroup_omm.cfg:ro
    ports:
      - "15432:5432"
    networks:
      - sales-api-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gaussdb", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  sales-api-network:
    driver: bridge

volumes:
  gaussdb_data:
  gaussdb_logs:
```

gaussdb          | loading security plugin ... ok
gaussdb          | update system tables ... ok
gaussdb          | creating snapshots catalog ... ok
gaussdb          | vacuuming database template1 ... ok
gaussdb          | copying template1 to template0 ... ok
gaussdb          | copying template1 to postgres ... ok
gaussdb          | freezing database template0 ... ok
gaussdb          | freezing database template1 ... ok
gaussdb          | freezing database postgres ... ok
gaussdb          | 
gaussdb          | WARNING: enabling "trust" authentication for local connections
gaussdb          | You can change this by editing pg_hba.conf or using the option -A, or
gaussdb          | --auth-local and --auth-host, the next time you run gs_initdb.
gaussdb          | 
gaussdb          | Success. You can now start the database server of single node using:
gaussdb          | 
gaussdb          |     gaussdb -D /var/lib/opengauss/data --single_node
gaussdb          | or
gaussdb          |     gs_ctl start -D /var/lib/opengauss/data -Z single_node -l logfile
gaussdb          | 
gaussdb          | could not create directory /var/log/opengauss/bin: Permission denied
gaussdb          | [2025-06-02 10:14:28.307][195][][gs_ctl]: gs_ctl started,datadir is /var/lib/opengauss/data 
gaussdb          | [2025-06-02 10:14:28.375][195][][gs_ctl]: waiting for server to start...
gaussdb          | .0 LOG:  [Alarm Module]can not read GAUSS_WARNING_TYPE env.
gaussdb          | 
gaussdb          | 0 LOG:  [Alarm Module]Host Name: 21bb1f6d4d84 
gaussdb          | 
gaussdb          | 0 LOG:  [Alarm Module]Host IP: 172.20.0.2 
gaussdb          | 
gaussdb          | 0 LOG:  [Alarm Module]Get ENV GS_CLUSTER_NAME failed!
gaussdb          | 
gaussdb          | 0 LOG:  [Alarm Module]Invalid data in AlarmItem file! Read alarm English name failed! line: 57
gaussdb          | 
gaussdb          | 0 WARNING:  failed to open feature control file, please check whether it exists: FileName=gaussdb.version, Errno=2, Errmessage=No such file or directory.
gaussdb          | 0 WARNING:  failed to parse feature control file: gaussdb.version.
gaussdb          | 0 WARNING:  Failed to load the product control file, so gaussdb cannot distinguish product version.
gaussdb          | The core dump path is an invalid directory
gaussdb          | 2025-06-02 10:14:28.511 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  when starting as multi_standby mode, we couldn't support data replicaton.
gaussdb          | gaussdb.state does not exist, and skipt setting since it is optional.2025-06-02 10:14:28.518 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]can not read GAUSS_WARNING_TYPE env.
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.518 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Host Name: 21bb1f6d4d84 
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.518 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Host IP: 172.20.0.2 
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.518 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Get ENV GS_CLUSTER_NAME failed!
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.518 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Invalid data in AlarmItem file! Read alarm English name failed! line: 57
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.523 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  loaded library "security_plugin"
gaussdb          | 2025-06-02 10:14:28.523 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] WARNING:  could not create any HA TCP/IP sockets
gaussdb          | 2025-06-02 10:14:28.523 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] WARNING:  could not create any HA TCP/IP sockets
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] WARNING:  No explicit IP is configured for listen_addresses GUC.
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  InitNuma numaNodeNum: 1 numa_distribute_mode: none inheritThreadPool: 0.
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  reserved memory for backend threads is: 220 MB
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  reserved memory for WAL buffers is: 128 MB
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  Set max backend reserve memory is: 348 MB, max dynamic memory is: 11065 MB
gaussdb          | 2025-06-02 10:14:28.532 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  shared memory 362 Mbytes, memory context 11413 Mbytes, max process memory 12288 Mbytes
gaussdb          | 2025-06-02 10:14:28.559 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [CACHE] LOG:  set data cache  size(402653184)
gaussdb          | 2025-06-02 10:14:28.571 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [CACHE] LOG:  set metadata cache  size(134217728)
gaussdb          | 2025-06-02 10:14:28.604 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [SEGMENT_PAGE] LOG:  Segment-page constants: DF_MAP_SIZE: 8156, DF_MAP_BIT_CNT: 65248, DF_MAP_GROUP_EXTENTS: 4175872, IPBLOCK_SIZE: 8168, EXTENTS_PER_IPBLOCK: 1021, IPBLOCK_GROUP_SIZE: 4090, BMT_HEADER_LEVEL0_TOTAL_PAGES: 8323072, BktMapEntryNumberPerBlock: 2038, BktMapBlockNumber: 25, BktBitMaxMapCnt: 512
gaussdb          | 2025-06-02 10:14:28.621 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  gaussdb: fsync file "/var/lib/opengauss/data/gaussdb.state.temp" success
gaussdb          | 2025-06-02 10:14:28.621 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  create gaussdb state file success: db state(STARTING_STATE), server mode(Normal), connection index(1)
gaussdb          | 2025-06-02 10:14:28.792 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  max_safe_fds = 983, usable_fds = 1000, already_open = 7
gaussdb          | The core dump path is an invalid directory
gaussdb          | 2025-06-02 10:14:28.793 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  user configure file is not found, it will be created.
gaussdb          | 2025-06-02 10:14:28.796 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  the configure file /usr/local/opengauss/etc/gscgroup_omm.cfg doesn't exist or the size of configure file has changed. Please create it by root user!
gaussdb          | 2025-06-02 10:14:28.796 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  Failed to parse cgroup config file.
gaussdb          | 2025-06-02 10:14:28.820 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] FATAL:  ERROR: could not create instr log directory "pg_perf": Permission denied
gaussdb          | 
gaussdb          | 2025-06-02 10:14:28.834 [unknown] [unknown] localhost 140134391069760 0[0:0#0]  0 [BACKEND] LOG:  FiniNuma allocIndex: 0.
gaussdb          | [2025-06-02 10:14:29.376][195][][gs_ctl]: waitpid 199 failed, exitstatus is 256, ret is 2
gaussdb          | 
gaussdb          | [2025-06-02 10:14:29.376][195][][gs_ctl]: stopped waiting
